### ISSUE TITLE
possibility to run a scan of logs and generate reports in a standalone way ( no jenkins, no github workflow ) 

### ISSUE THREAD

**Issue by ysmaoui** [uhafner/quality-monitor#8]
Hi, 

is there a possibility to run the scan of logs and the generation of reports without the need for jenkins or github workflows and actions? 
maybe from a container or a packaged application?

thanks

**Comment by uhafner** [comment]
You can start the quality-monitor by using `docker run`. But since the program reports the results to GitHub in Markdown, there is no plain text output available yet. How do you plan to use such an approach?

**Comment by ysmaoui** [comment]
the ideal scenario is to give a log file as input and get some report ( html? ) as output 
without any dependency on the workflow system that is used

**Comment by uhafner** [comment]
I see. This is not possible in the moment. But one could design a new backend that simply generates a Markdown report (already supported). HTML reports need some extra work.

I'm not sure if this should be part of the `quality-monitor` project itself as it is supposed to be used as GitHub action only? One could create a new CLI project that uses https://github.com/uhafner/autograding-model to create the reports.
